name: astrostat-school
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - jupyter-book<2
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - astropy
  - requests
  - emcee
